# R Matrix Exercises

Through these exercises we will review the matrix data structure and perhaps introduce you to a few ideas for you to discover on your own! Just answer the questions below written in bold:

**Ex 1: Create 2 vectors A and B, where A is (1,2,3) and B is (4,5,6). With these vectors, use the cbind() or rbind() function to create a 2 by 3 matrix from the vectors. You'll need to figure out which of these binding functions is the correct choice.**

In [2]:
a <- c(1:3)
b <- c(4:6)
rbind(a,b)

[,1] [,2] [,3]
a 1    2    3   
b 4    5    6

**Ex 2: Create a 3 by 3 matrix consisting of the numbers 1-9. Create this matrix using the shortcut 1:9 and by specifying the nrow argument in the matrix() function call. Assign this matrix to the variable mat**

In [3]:
mat <- matrix(1:9,byrow=T, nrow=3)
mat

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

**Ex 3: Confirm that mat is a matrix using is.matrix()**

In [5]:
is.matrix(mat)

[1] TRUE

**Ex 4: Create a 5 by 5 matrix consisting of the numbers 1-25 and assign it to the variable mat2. The top row should be the numbers 1-5.**

In [9]:
mat2 <- matrix(1:25,byrow=T,nrow=5)
mat2[2:3,2:3]

[,1] [,2]
[1,]  7    8  
[2,] 12   13

**Ex 5: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[7,8]

[12,13]

In [10]:
mat2[4:5,4:5]

[,1] [,2]
[1,] 19   20  
[2,] 24   25

**Ex 6: Using indexing notation, grab a sub-section of mat2 from the previous exercise that looks like this:**

[19,20]

[24,25]

**Ex 7: What is the sum of all the elements in mat2?**

In [11]:
sum(mat2)

[1] 325

**Ex 8: Ok time for our last exercise! Find out how to use runif() to create a 4 by 5 matrix consisting of 20 random numbers (4*5=20).**

In [13]:
mat3 <- matrix(runif(20,min=0,max=100),nrow=4)
mat3

[,1]     [,2]     [,3]      [,4]     [,5]    
[1,] 83.08865 83.63045  8.391512 40.35205 94.53153
[2,] 37.37466 60.43500 68.741720 79.51452 48.27730
[3,] 12.18911 51.13280 24.409477 85.81744 31.72549
[4,] 17.35641 15.69345  2.441680 71.82397 50.33090